### ISSUE TITLE
Can't use : character in title

### ISSUE THREAD

**Issue by bblonski** [asciidoctor/asciidoctor.js#101]
asciidoctor.js fails to parse the `:` character in the title of a document.

**Comment by mojavelinux** [comment]
In what way is it failing. I tried it and it works for me. In fact, the main example in this project loads the README.adoc, which has a colon in the title and it works. Can you test the example?

**Comment by mojavelinux** [comment]
Or are you saying it isn't making a subtitle?

**Comment by bblonski** [comment]
I'll be honest, I noticed this in AsciidocFX where I reported it first.  They said it was due to a bug in the underlying asciidoctor.js and referred me here, but I can't reproduce it with just asciidoctor.js it so it does appear to be on their end.

**Comment by bblonski** [comment]
I'm not good enough with ruby and javascript to test this myself, but could you test this with the docbook backend?  HTML generation works fine, but it looks like the docbook output is blank.

**Comment by mojavelinux** [comment]
Aha! Thanks for the clarification. Now we know where to look.

Chances are that AsciidocFX is using the old API for parsing the title, since that API changed in 1.5.0. The bug might be in Asciidoctor.js or it might be in AsciidocFX. But now that we know it's DocBook, it makes more sense because DocBook does use the subtitle feature.

**Comment by bblonski** [comment]
Sorry about that, I should have clarified.  I was trying to generate PDFs
and AsciidocFX hides the docbook generation step, so it didn't occur to me
at first.

**Comment by Mogztter** [comment]
@mojavelinux @bblonski So this issue belongs to AsciidocFX or do we have to fix something in Asciidoctor.js ?

**Comment by mojavelinux** [comment]
It has to be something in AsciidocFX (if it's even still a problem) because there's no code in Asciidoctor.js (different from Asciidoctor core) that would determine one way or another how this is parsed. It's in the converter, and that just depends which version of Asciidoctor that AsciidocFX is using.

**Comment by bblonski** [comment]
Yeah, I just checked again.  It is still an issue in AsciidocFX.  I believe the issue is with docbook conversion.  The colon is not valid for docbook xml.

**Comment by Mogztter** [comment]
Ok in that case, I'm closing the issue, thanks for the clarification.
