### ISSUE TITLE
Add epub and pdf converters to npm module too

### ISSUE THREAD

**Issue by bguiz** [asciidoctor/asciidoctor.js#102]
Could this be done by transpiling the libraries using Opal too?

**Comment by Mogztter** [comment]
Hi @bguiz, Asciidoctor pdf and epub3 are written entirety in Ruby so I think it's possible.
But there will be challenges ! //cc @mojavelinux

**Comment by mojavelinux** [comment]
Actually, I don't think transpiling is the right approach in this case. Both Asciidoctor EPUB3 and Asciidoctor PDF rely on complex libraries that don't lend themselves well to transpiling and the result will likely be very slow.

A better solution here is to move forward with linking Asciidoctor.js to native JavaScript solutions for EPUB3 and PDF. For EPUB3, we could look at what GitBook.io is using since they are producing EPUB3 in JavaScript (as far as I understand). For PDF, we'd hook to something like jspdf (https://github.com/MrRio/jsPDF).

There's a chance we can transpile Asciidoctor PDF just to see how it goes, but EPUB3 uses Nokogiri, so that's probably going to throw up a roadblock.

**Comment by bguiz** [comment]
@mojavelinux @Mogztter Well I'm certainly keen to have these Asciidoctor plugins available to use with NodeJs!

**Comment by Mogztter** [comment]
> For EPUB3, we could look at what GitBook.io is using since they are producing EPUB3 in JavaScript (as far as I understand)

I give GitBook.io a try but they are using [ebook-convert](http://manual.calibre-ebook.com/cli/ebook-convert.html) command line:

> eBook: You need to have ebook-convert installed. You can specify the eBook filename as the second argument, otherwise book will be used.

**Comment by hypery2k** [comment]
any plans for PDF?

**Comment by mojavelinux** [comment]
As Opal improves, so those the chance of cross compiling Asciidoctor PDF. I'm have no idea how the performance is going to translate, though, since Asciidoctor PDF uses very deep recursion.

I still think a better approach is to use a native PDF library for JavaScript and recreate the converter. That's a big undertaking, so maybe that's a separate effort from transpiling. Either way, we aren't going to know until we try. Otherwise, we're just guessing.

**Comment by bguiz** [comment]
I came across an interesting ideas around ASTs for documents, and a markdown implementation by @wooorm 

There's some discussion here:
https://github.com/wooorm/unist/issues/8

If we do consider as proper rewrite instead of a transpiled solution, as @mojavelinux has suggested, it will be worth having an asciidoc parser that outputs an AST, and then have PDF and EPUB writers that take in this as input.

Thoughts?

**Comment by bguiz** [comment]
@mojavelinux that's excellent - I'm not so familiar with the asciidoc codebase, mind pointing me in the right direction (at perhaps a couple of files) ... say at the bits which create said ASTs?

**Comment by mojavelinux** [comment]
The real question is whether you want to make this output in Ruby or JavaScript.

If you're interested in doing it in JavaScript, I recommend studying @Mogztter's work on the Reveal.js converter. That essentially accounts for every node and taps deep into the AST. See https://github.com/asciidoctor/asciidoctor-reveal.js/tree/master/templates/jade for the templates that handle each node.

You don't have to use templates. It's possible to create a custom converter that takes the AST model and walks through it, converting each node in turn.

The document model in Asciidoctor is definitely still evolving. Asciidoctor did not start out with the goal of creating a model that represents the entire structure, so we're gradually maturing into it. In some cases, there are still assumptions that it's converting to a string. The work on Asciidoctor PDF as well as the work on the tooling has helped break up some of those assumptions.

**Comment by Mogztter** [comment]
I think https://github.com/bpampuch/pdfmake is the most complete library (based on https://github.com/devongovett/pdfkit with tables, columns, lists, images...)

**Comment by mojavelinux** [comment]
Generating a PDF is no small task, but I do think that even getting this converter to work a little will help us explore the Asciidoctor.js API and understand better where we need to improve it. In other words, it's a useful exercise even if just for experimentation.

The main challenge with creating a PDF is dealing with page boundaries. They are a huge pain. Every line you write has the potential of getting caught up at a page boundary and there's a ton of logic you need to implement to do something sane. I'm struggling with that in Asciidoctor PDF every day.

**Comment by Mogztter** [comment]
I have a prototype to convert an AsciiDoc document to PDF using web technologies: https://github.com/Mogztter/asciidoctor-pdf.js

I'm closing this issue since we won't implement a PDF converter or an EPUB converter inside Asciidoctor.js (but as additional converters).
If someone want to work on one converter I can provide assistance 😉
