### ISSUE TITLE
rendering code

### ISSUE THREAD

**Issue by Bloggerschmidt** [asciidoctor/asciidoctor.js#103]
When I write something like 

```asciidoc
[source, html]
____
<div id="superid">sometext</div>
____ 
```

it renders something like:

```html
<pre><code>
<div id="superid">sometext</div>
</code ></pre>
```

But it should render like this:

```html
<pre>
<div id="superid">sometext</div>
</pre>
```

without `<code>`. Is there a workaround to avoid this?

**Comment by Mogztter** [comment]
Hi @Bloggerschmidt,

AFAIK the output is correct because this is a preformatted text of `<code>`. Syntax highlighting libraries expect this pattern (see https://highlightjs.org/usage/)

If you just want preformatted text (whitout syntax highlighting) you can use literal block: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code

```asciidoc
----
<div id="superid">sometext</div>
----
```

should render:

```html
<pre><div id="superid">sometext</div></pre>
```

Cheers,
Guillaume

**Comment by anthonny** [comment]
@Mogztter thank you ;)

**Comment by Bloggerschmidt** [comment]
@Mogztter Thank you for pointing this out.
