### ISSUE TITLE
fromHash doesn't appear to deal  with numerical keys properly

### ISSUE THREAD

**Issue by djencks** [asciidoctor/asciidoctor.js#1034]
include processors get their unnamed attributes delivered with numerical keys 1, 2, .... However, in asciidoctor.js the attributes map is empty.  The method at fault appears to be:

```
const fromHash = function (hash) {
  const object = {}
  if (hash) {
    const data = hash.$$smap
    for (const key in data) {
      const value = data[key]
      object[key] = value === Opal.nil ? undefined : value
    }
  }
  return object
}
```

Dan suggests it should be more like:
```
for (var key of keys) {
    if (key.key == null) {
      object[key] = data[key]
    } else {
      object[key.key] = key.value
    }
  }
```

(asciidoctor-core-api)

**Comment by Mogztter** [comment]
> include processors get their unnamed attributes

Are we talking about positional attributes? If that's the case, we've decided to remove them from `getAttributes` (and eventually introduce a new function `getPositionalAttributes`), see the original discussion: https://github.com/asciidoctor/asciidoctor.js/pull/491#issuecomment-387701240

Feel free to submit a pull request to add the `getPositionalAttributes` function that should return a 1-based array?

```js
getPositionalAttributes[1] // return the first positional attribute
```

**Comment by mojavelinux** [comment]
Not quite. The issue is that when fromHash converts the Hash (Opal Hash to JavaScript object), it skips any integer keys. (Opal has to store them differently to preserve the type). The parser uses the integer keys to store positional (aka unnamed) attributes. This is the only way for an include processor to access these attributes from the directive. (But these attributes can be general useful in other contexts as well).

**Comment by Mogztter** [comment]
> Not quite. The issue is that when fromHash converts the Hash (Opal Hash to JavaScript object), it skips any integer keys. 

Indeed but the JavaScript object keys has to be strings. As far as I remember, we were unsure about converting numeric keys to strings (i.e. `1` to `"1"`).

> The parser uses the integer keys to store positional (aka unnamed) attributes. This is the only way for an include processor to access these attributes from the directive.

When the `process` method is called with an attributes Hash (and automatically converted to JavaScript object)?
It's true that in this case, the `attributes` object will not contain positional attributes. Maybe a `$positional` key in the JavaScript object that returns an array? (I'm using the symbol `$` to avoid conflicts with a named attribute).


```js
attributes.$positional[0]
```

**Comment by mojavelinux** [comment]
> Indeed but the JavaScript object keys has to be strings.

Right, that's why Opal stores them differently.

> As far as I remember, we were unsure about converting numeric keys to strings (i.e. 1 to "1").

Yes, this is still a challenge / open question. But I don't think dropping them is correct either.

> Maybe a $positional key in the JavaScript object that returns an array?

I like that idea. (That might even be something we backport to core eventually).

The choice to make these keys integers was something that came from AsciiDoc Python, but I think it's worth rethinking that legacy.

**Comment by mojavelinux** [comment]
...another idea would be to prefix each numeric key with `$`.

**Comment by djencks** [comment]
I like the $positional key idea, as it clearly separates the positional attributes from the named attributes, and lets you access the positional attributes by position rather than encoded "pseudo-position".

**Comment by Mogztter** [comment]
I think `$positional` is a good solution.
Regarding the starting index, we should probably use 1 because the first positional attribute index is 1.

```js
attributes.$positional[1] // first positional attribute
```

### Alternative solutions


#### Array that starts at 0

```js
attributes.$positional[0] // first positional attribute
```

Since the API is using 1 as the first positional attribute, it would be confusing to use index 0 to get the first positional attribute. Consider the following:

```js
resolveAttributes('1:name')
// ...
attributes.$positional[1] // name attribute?
```

#### JavaScript object

```js
attributes.$positional['1']
```

I think it would be less logical to use a String rather than an index.

#### $ prefix key

```js
attributes.$1
```

I think that using an Array is more useful because you can apply operations on it (`slice`, `map`, `reverse`, `join`...).
Having said that, the syntax is nice because you can access the positional attribute with the dot notation and the code reads (surprisingly) well. Arguably, the `$` prefix feels a bit "magical" but I would be open to add this accessor as an alias (i.e. both `attributes.$positional[1]` and `attributes.$1` will return the first positional attribute).

What do you think?

**Comment by mojavelinux** [comment]
Having read your proposal, I'm now in favor of the $positional key. Since it's already an abstraction, it seems perfectly reasonable to me that it's stored using a normal, 0-based array. Even though positional attributes are named using 1-based keys, I think most (if not all) programmers will be able to make this stretch of logic.

**Comment by Mogztter** [comment]
> Since it's already an abstraction, it seems perfectly reasonable to me that it's stored using a normal, 0-based array

That's a fair point.

> Having read your proposal, I'm now in favor of the $positional key.

So your vote goes in favor of:

```js
attributes.$positional[0] // first positional attribute
```

With or without adding `$` prefixed keys (as "alias")?

```js
attributes.$positional[0] // first positional attribute
attributes.$1 // first positional attribute
```

Adding `$` prefixed keys might add to the confusion... 🤔

**Comment by mojavelinux** [comment]
> Adding $ prefixed keys might add to the confusion... thinking

I agree. Let's not start with them there. We can always add them later if we feel it's necessary.

**Comment by Mogztter** [comment]
@mojavelinux On some Nodes, I get a `nil` positional attribute. For instance, the following table:

```adoc
[%header%footer%autowidth]
|===
|This is a header cell

|This is a normal cell

|This is a footer cell
|===
```

will return the following (Opal) Hash as attributes:

```js
constructor {
  '$$smap':
   { tablepcwidth: 100,
     colcount: 1,
     rowcount: 3,
     'header-option': '',
     'footer-option': '',
     'autowidth-option': '',
     style: 'table' },
  '$$map':
   [Object: null prototype] { '3': { key: 1, key_hash: 3, value: [constructor] } },
  '$$keys':
   [ 'tablepcwidth',
     'colcount',
     'rowcount',
     { key: 1, key_hash: 3, value: [constructor] },
     'header-option',
     'footer-option',
     'autowidth-option',
     'style' ]
}
```

Notice the `$$map` key that contains:

```js
[Object: null prototype] { '3': { key: 1, key_hash: 3, value: [constructor] } }
```

`[constructor]` is a bit misleading but the value is actually `Opal.nil`. In other words, the first positional attribute is defined and the value is `nil`.
I can add extra code to remove it but I want to make sure that this is intended. If not, we could remove it from Asciidoctor core to avoid extra work on Asciidoctor.js.

For now, I return the following JavaScript object:

```js
{
  tablepcwidth: 100,
  colcount: 1,
  rowcount: 3,
  'header-option': '',
  'footer-option': '',
  'autowidth-option': '',
  style: 'table',
  '$positional': [ undefined ]
}
```

But `'$positional': [ undefined ]` does not feel right...?

**Comment by mojavelinux** [comment]
When the shorthand attribute syntax is used without a block name/style (for example, only a role like `.rolename`), then the first positional attribute ends up with a value of nil. This is kept so that the other positional attributes don't lose their positions. In the Asciidoctor.js public API, I think this should be represented as undefined. If it's the only positional attribute (i.e., `[ undefined ]`), I suppose the array can be coerced to empty.

**Comment by Mogztter** [comment]
> When the shorthand attribute syntax is used without a block name/style (for example, only a role like .rolename), then the first positional attribute ends up with a value of nil. This is kept so that the other positional attributes don't lose their positions.

Ok so the first positional is the "undefined" block name/style?

> In the Asciidoctor.js public API, I think this should be represented as undefined. If it's the only positional attribute (i.e., [ undefined ])

👍 

> I suppose the array can be coerced to empty.

We might but now `[ undefined ]` makes sense.
