### ISSUE TITLE
Asciidoctor validation

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#107]
Is there any way to test a asciidoc content is valid or not (which line/column/message)?

If possible we want to integrate it to Asciidocfx.

**Comment by mojavelinux** [comment]
The best way atm is to convert it to DocBook and see if the DocBook is invalid. Having said that, it's somewhat difficult to create bad AsciiDoc because the parser only interprets good syntax. What doesn't make sense just remains as raw source. Of course, there are plenty of edge cases where the syntax can go wrong...so I'm not saying validation isn't necessary.

**Comment by rahmanusta** [comment]
Thanks for detailed infos @mojavelinux . I will try with XML validation
