### ISSUE TITLE
Enhance return value defintions in AbstractNode

### ISSUE THREAD

**Issue by bitPogo** [asciidoctor/asciidoctor.js#1118]
Some return values are marked as `SOMETYPE | void` and they should be `SOMETYPE | undefined`.

**Comment by Mogztter** [comment]
I need to check what `$resolve_subs` actually returns. Here's the original Ruby code:

https://github.com/asciidoctor/asciidoctor/blob/5845c665c8f8eec0c95154b00adc32c383fc4efc/lib/asciidoctor/substitutors.rb#L1164

I believe the value should be `Opal.nil`, so we should probably also update the implementation to return `undefined` instead of `Opal.nil`.

And yes, we should replace `SOMETYPE | void` by `SOMETYPE | undefined`.
To be honest, I don't recall why I declared `void`...

**Comment by bitPogo** [comment]
No worry...at a file this large mistakes happen...
