### ISSUE TITLE
Highlighting source code blocks in the browser. Can it be done?

### ISSUE THREAD

**Issue by kdekooter** [asciidoctor/asciidoctor.js#1194]
I would like to do all AsciiDoc processing in the browser - client-side that is. Basic conversion works fine with the `asciidoctor.convert` method. However I am having a hard time creating syntax highlighting (preferably with `highlight.js`) for source code blocks. 

Am I missing some piece of information? Or is this impossible?

**Comment by Mogztter** [comment]
Hi @kdekooter :wave: 

It's possible, that's basically what the [Asciidoctor Browser Extension](https://github.com/asciidoctor/asciidoctor-browser-extension) is doing.
I believe you are converting the AsciiDoc document to [embedded output](https://docs.asciidoctor.org/asciidoctor/latest/api/convert-strings/#embedded-output)? If so, you will need to manually inject Highlight.js script and styles into the page (when syntax highlighting is enabled: `doc.isAttribute('source-highlighter')`).

**Comment by kdekooter** [comment]
Thanks for your swift response @Mogztter. How do I "manually inject" the script? Is this what you mean?

```
  const syntaxHighlighting = () => {
    document.body.querySelectorAll('pre.highlight > code').forEach((node) => {
      const match = /language-(\S+)/.exec(node.className)
      if (match !== null && hljs.getLanguage(match[1]) !== null) {
        hljs.highlightBlock(node)
      } else {
        node.className += ' hljs'
      }
    })
  }
```

A bit of context: I am the creator of notestack.io, "The Developer's Notebook". Notes can be created in Markdown, but I want to add additional source languages. 

The markdown editor contains an interactive preview of the text you are typing. An AsciiDoc variant should have the same functionality. So I do not want to rely on server side components or browser plugins. It should all happen in the app ;-).

**Comment by kdekooter** [comment]
Follow up: it is working with the same "post-processing" step as the browser extension uses. 

Would be great though if this functionality could be included as some kind of plugin in the `convert` method.

**Comment by mojavelinux** [comment]
> Would be great though if this functionality could be included as some kind of plugin in the convert method.

That would be a build time syntax highlighter (see https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/#client-side-vs-build-time). That is possible to implement in Asciidoctor.js using a syntax highlighter adapter (which is something that could be provided). But if you rely on using highlight.js client-side (meaning on page load), then fundamentally it cannot be part of convert. Because, in that case, highlight.js is operating on the HTML that the convert method produces. They are two separate steps. This would be true for Markdown as well.

**Comment by kdekooter** [comment]
I get that it would take a second pass to process. Only now it looks a bit clunky - I first convert the AsciiDoc to HTML, put that in a `<section>` in the page and then target this section with the highlighter. 

`marked` on the other hand does it like this (could well be that they do two passes internally of course):
```
marked(this.value, {
            sanitize: false,
            breaks: true,
            gfm: true,
            tables: true,
            headerPrefix: 'md-',
            highlight: function(code, language) {
              return hljs.highlightAuto(code, [language]).value
            },
```

**Comment by mojavelinux** [comment]
marked is providing an abstraction layer above what Asciidoctor is providing. You could certainly create such a library that uses Asciidoctor in this way (or perhaps Asciidoctor could add a browser-oriented API that bundles this functionality). But it's not something that Asciidoctor core itself is going to do because Asciidoctor doesn't insert HTML into a page.

**Comment by kdekooter** [comment]
To be clear: _I_ am the one inserting HTML into a page here 😄 , marked is only converting markdown to an HTML string.

**Comment by mojavelinux** [comment]
I see how it's working now. Then that is the equivalent to the syntax highlighter adapter I mentioned. If Asciidoctor.js wants to provide a syntax highlighter adapter that runs highlight.js during conversion, it certainly could. Or anyone could create that adapter and combine it with Asciidoctor.js. The capability is there.
