### ISSUE TITLE
Release opal-npm-wrapper fix

### ISSUE THREAD

**Issue by vanjan** [asciidoctor/asciidoctor.js#128]
Hi guys, could you please release this @143a6867 fix? I'm working in an environment where git protocol is blocked an am unable to install packages that use asciidoctor.js@1.5.2.

**Comment by Mogztter** [comment]
Sure.
@mojavelinux @anthonny Should we release a `1.5.2.100` (using the same versioning as the Chrome Extension) ?

**Comment by mojavelinux** [comment]
I'd rather just make it 1.5.2.1.

**Comment by anthonny** [comment]
wdyt about 1.5.2-1 (or 1.5.2-100)?

 SemVer http://semver.org/

**Comment by mojavelinux** [comment]
Yes, 1.5.2-1. (RubyGems doesn't allow this part of semver, which is why I have a habit of using the dot where it should be a hyphen).

**Comment by Mogztter** [comment]
I like the syntax but I think in our case this is misleading:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. 

> Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

If we want to follow the SemVer, we should release a 1.5.3-(something) but this is also misleading since this version will not use Asciidoctor core 1.5.3.
I think most of the projects in the Asciidoctor repository (all of them ?) are using the Asciidoctor core version as a base version. The clear benefit is that we know for sure what version of Asciidoctor core is being use. The drawback is that SemVer becomes much harder since `major.minor.patch` are already taken.

On another project we decided to have different version number between core and plugins/extensions/bindings. On the README, we have a simple table:

Plugin version | Core version
------------------- | -------------
`4.x` (latest `4.0.2`) | `1.5.3`
`3.x` (latest `3.3.1`) | `1.5.2`
`2.x` (latest `2.1.8`) | `1.5.2`

The main benefit is that maintainers of plugins can release as often as they want. They can also introduce breaking changes for the same core version.

So I believe there are two options:

 1. Use different version between core and plugins in order to respect SemVer
 2. Use a 4 digits version (first 3 are the core version and the 4th is the plugin version)

**Comment by vanjan** [comment]
As a user, I would prefer option 1: Use different version between core and plugins in order to respect SemVer. It's important to be able to rely on a standard.

**Comment by mojavelinux** [comment]
Here's another option to consider. I think it's fine for modules to move ahead of the core version in prereleases. Otherwise, everything has to wait for core to be released to start having prereleases, and that just makes no sense. So we'd only guarantee the alignment with core when the final version is released. You can then use all the prerelease syntax of SemVer leading up to the final release of the module. (so this release can be `1.5.3-<something>`).

Part of the reason we're in this situation is because core releases are moving too slow. It's been hard for me to balance expectations with releases, but I'm working to get there. I think we should assume (to put some pressure on it) that core will move a bit faster.

I also don't think that the version alignment has to be down to the patch version. The idea all along was to let the patch version (the 3rd position) float and the alignment be on the minor version only (e.g., 1.5). (We could also start to make bigger shifts in the versions of core to make that more comfortable).

We did try to allow the versions between core and the gradle plugin to vary widely and it was massively confusing. So it seems to me that the right answer is to have alignment to a point (e.g., 1.5), but not overdo it. But I'm still trying to figure this out myself, so that's just my hunch.

**Comment by vanjan** [comment]
Sounds like a good compromise.

**Comment by Mogztter** [comment]
> We did try to allow the versions between core and the Gradle plugin to vary widely and it was massively confusing.

I think it was massively confusing because version `1.5.2` is used everywhere. Most of the projects are using core version so users expect the version of the project to be the version of core. 

Using a unique version number is easier and thus more user friendly at first but will become very confusing. For instance, if I create a new plugin, the first version will be `1.5.(something)` even if my plugin is unstable or the API is subject to change.
Another recent example, in Asciidoctor.js, upgrading to Opal 0.8.0 cause some breaking changes, but major and minor version will remain unchanged.

Core version is a key information and may be include in the build metadata:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version.
http://semver.org/

Something like `1.2.5+core1.5.2`. 
A bit verbose but this avoid confusion because the version of core is next to the version of the plugin.

> But I'm still trying to figure this out myself

Me too but I think we should embrace SemVer. Also there are very few projects where core version is the base version of plugins.

**Comment by Mogztter** [comment]
Maybe something to discuss http://discuss.asciidoctor.org/ ?
I don't want to "waste" time but I think this is important to come to an agreement and share a common guideline.

**Comment by vanjan** [comment]
Any chance of releasing this fix?

**Comment by Mogztter** [comment]
@vanjan Yes I'll do a `1.5.3-1` release this week

The discussion about SemVer is global and I don't want to hold the release because of that.
So for now, I will just stick with the current versioning schema :smile:

**Comment by vanjan** [comment]
Great, thanks a lot!

**Comment by vanjan** [comment]
How's that going? :)

**Comment by Mogztter** [comment]
I'm now a maintainer of the package, so version `1.5.3-preview.1` will soon be available :smile:

**Comment by Mogztter** [comment]
Done! https://www.npmjs.com/package/asciidoctor.js

**Comment by vanjan** [comment]
Thanks!

**Comment by mojavelinux** [comment]
The version discussion is now underway on the mailinglist for those following along.

http://discuss.asciidoctor.org/Projects-versioning-strategy-td3841.html
