### ISSUE TITLE
user manual: jsdoc not browsable since version 2.2.1

### ISSUE THREAD

**Issue by mburri** [asciidoctor/asciidoctor.js#1397]
I tried to browse the jsdoc in the user manual - without success: https://asciidoctor.github.io/asciidoctor.js/2.2.5/. 

Clicking a link in the table of contents has no effect...

I checked for older versions and noticed that the links work in version 2.2.0 (https://asciidoctor.github.io/asciidoctor.js/2.2.0/) but not since 2.2.1 (https://asciidoctor.github.io/asciidoctor.js/2.2.1)

**Comment by Mogztter** [comment]
Nice catch!
This is actually a "bug" in https://github.com/documentationjs/documentation

Here's the culprit:
 
```js
/**
 * Generate and assign caption to block if not already assigned.
 * 
 * (...)
 *
 * The parts of a complete caption are: <prefix> <number>. <title>
 * 
 * (...)
 */
AbstractBlock.prototype.assignCaption = function (value, captionContext)
// ...
```

The problem is that `"<prefix> <number>. <title>"` is unescaped!
As a result, the HTML page produced by `documentation` is invalid. That's why there's nothing after the `assignCaption` function.

It's possible to use backticks to indicate that `"<prefix> <number>. <title>"` must be espaced:


```js
/**
 * Generate and assign caption to block if not already assigned.
 * 
 * (...)
 *
 * The parts of a complete caption are: `<prefix> <number>. <title>`
 * 
 * (...)
 */
AbstractBlock.prototype.assignCaption = function (value, captionContext)
// ...
```

**Comment by Mogztter** [comment]
It should be fixed now.

For reference: 
265069d2def8ca2a1222348dde4f3f1b5ab7c736 (v2.2.x branch)
7d1c64bec31e0b9873a9370ec756ad271b5f8da5 (master)

And the commit on the `gh-pages` branch: ed84c01

**Comment by Mogztter** [comment]
https://asciidoctor.github.io/asciidoctor.js/master/ also fixed!

**Comment by mburri** [comment]
works now as expected. thanks!

**Comment by Mogztter** [comment]
Thank *you* for reporting and confirming that this issue is now fixed!
