### ISSUE TITLE
Request: Extension for Azure DevOps Server/Services

### ISSUE THREAD

**Issue by dennisl68-castra** [asciidoctor/asciidoctor.js#1469]
So, is there an extension of this AsciiDoc-implementation in the work for Azure DevOps Server/Services?

**Comment by Mogztter** [comment]
Hello @dennisl68-castra,

I'm not aware of any extension for Azure DevOps Server/Services based on Asciidoctor.js but I support this idea.
However, I won't have time to work on it so feel free to take this one if you are interested.

I think you should ask in the community chat at https://asciidoctor.zulipchat.com, maybe it will spark interest (or maybe someone in the community has prior experience with Azure DevOps extension development and can help you get started).

I'm closing this issue since this extension won't be implemented in this repository.
