### ISSUE TITLE
Load nodejs adapter when running under node

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#155]
Opal provides a [nodejs adapter](https://github.com/opal/opal/blob/master/stdlib/nodejs.rb) that implements IO operations when running under node. We should consider loading this adapter instead of our own custom logic for node (and use our custom logic for all other platforms).

(If we decide not to use it, we should document that this is intentional).

**Comment by mojavelinux** [comment]
Basically, evaluate it and decide what you think is best.

**Comment by Mogztter** [comment]
:+1: 

Asciidoctor.js `opal_ext` and Opal are converging (see [stdlib/opal/platform.rb](https://github.com/opal/opal/blob/master/stdlib/opal/platform.rb)) and we should be able to totally remove `opal_ext` directory in a near future: 
 * https://github.com/opal/opal/issues/1221
 * https://github.com/opal/opal/issues/1219
 * https://github.com/opal/opal/issues/1218

I will schedule this enhancement for Asciidoctor.js 1.5.4 because Asciidoctor.js 1.5.3 already have a lot of changes :smile: 

I think we will need to have one `file.rb` per runtime to follow the same pattern as Opal. Currently the `read` method handles Nashorn, Node.js and browsers runtimes in the same file.

**Comment by mojavelinux** [comment]
+1

**Comment by mojavelinux** [comment]
Are we ready for this change yet? Now that we have real file IO in Asciidoctor / Asciidoctor.js, we need methods like `File.file?`. I see that this method exists in the nodejs adapter.

One way or another, for the next release, we'll need `File.file?` defined in the node environment. If we want to do that as a one-off, let me know and I'll file a separate issue.

**Comment by Mogztter** [comment]
The `nodejs` module is loaded when the platform is `nodejs`: https://github.com/asciidoctor/asciidoctor.js/blob/607282cb02414129c921a9be50ddf3eb76329537/lib/asciidoctor/opal_ext.rb#L64-L66

The default implementation in `lib/asciidoctor/opal_ext/file.rb` should be overridden.
I think we can close this issue.

**Comment by mojavelinux** [comment]
I'm glad to hear it's integrated!

However, I think the require later in the file is overriding this code. Perhaps that needs to be a dynamic require.

Either way, you'll now be able to verify with a test. When running in node, if the include file can't be found (an invalid path), then it should show a warning, not cause the program to abort. This assumes you are running against Asciidoctor master, which updates the include logic.

**Comment by mojavelinux** [comment]
I can confirm the code in nodejs is being overridden by our opal_ext/file. If I delete that code, then File.file? returns false when a file doesn't exist. Otherwise, it returns true (since our method is hardcoded to return true).
