### ISSUE TITLE
Support deck.js backend

### ISSUE THREAD

**Issue by nawroth** [asciidoctor/asciidoctor.js#16]
I guess supporting multiple backends would make sense, but I find the case of slides especially interesting to be able to render directly in the browser.

Possibly related to #5.

**Comment by Mogztter** [comment]
Asciidoctor.js is now working great with custom backend and especially with Reveal.js https://github.com/asciidoctor/asciidoctor-reveal.js

If someone is interested, I can help with setting the build to produce a JavaScript version of the Asciidoctor Deck.js backend: https://github.com/asciidoctor/asciidoctor-deck.js

I'm closing this issue because I believe that on Asciidoctor.js side, we do have all we need to support a Deck.js backend :grinning: :tada:

**Comment by mojavelinux** [comment]
Agreed. I really, really dislike deck.js and I'd prefer it if we didn't spend community resources on it. The focus should be on reveal.js or bespoke.
