### ISSUE TITLE
Custom stylesheet not included

### ISSUE THREAD

**Issue by bgorholt** [asciidoctor/asciidoctor.js#1644]
I am trying to add a [custom style sheet](https://docs.asciidoctor.org/asciidoctor.js/latest/extend/stylesheets/#apply-theme) to a basic asciidoc conversion. This is the stylesheet:

```css
/* styles.css */
.foobar {
    color: '#ff00ff';
}
```

And here is a node.js script where the css file is included during adoc conversion:

```js
const Asciidoctor = require('asciidoctor')

const asciidoctor = Asciidoctor()

const content = `
:stylesheet: styles.css

[foobar]#hello, world#
`
const html = asciidoctor.convert(content, { 'attributes': { 'stylesheet': 'styles.css' } })

console.log(html)
```

The output then is 

```html
<div class="paragraph">
<p><span class="foobar">hello, world</span></p>
</div>
```

I would expect the foobar class definition to be included in the generated HTML. Is my assumption wrong or is there some error in the way that asciidoctor is used in the code snippet?

**Comment by Mogztter** [comment]
Hey!

When converting a string, Asciidoctor does not output a standalone document by default. Instead, it generates embedded output. 
https://docs.asciidoctor.org/asciidoctor/latest/api/convert-strings/#convert-an-asciidoc-string

If you want to generate a standalone document (i.e., complete HTML page) you need to add the `standalone` option:

```js
const html = asciidoctor.convert(content, { attributes: { stylesheet: 'styles.css' }, standalone: true })
```

If you want to embed the stylesheet in your HTML page (instead of linking to the stylesheet) then you will also need to set the safe mode to 'safe' :


```js
const html = asciidoctor.convert(content, { attributes: { stylesheet: 'styles.css' }, standalone: true, safe: 'safe' })
```

https://docs.asciidoctor.org/asciidoctor/latest/safe-modes/#safe

In the future, please ask usage questions about Asciidoctor.js in the #users/asciidoctor.js stream of the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). The issue tracker is reserved for reporting confirmed bugs and new feature proposals. Thanks!

**Comment by bgorholt** [comment]
Thank you, and gotcha - [continuing](https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/Cannot.20embed.20stylesheet.20into.20generated.20HTML) the topic on Zulipchat now.
