### ISSUE TITLE
Support async/promise in extension API/registration

### ISSUE THREAD

**Issue by Ayowel** [asciidoctor/asciidoctor.js#1731]
To my knowledge, the current extension API endpoints do not support returning Promises, on processor calls.

This makes the implementation of extensions that need to fetch data dynamically impossible (e.g.: statically including remote data sources, generating bibliography references from DOI, or implementing a web version of asciidoctor-bibtex without having the full "workspace" in-memory).

Additionally, this makes modular loading impossible (with the asciidoctoc-bibtex example: CSL styles are 33MB, which is an insane amount of data to load upfront considering that only 2K of it will be used, yet the style used is configured in the document and there is no way to asynchronous load a single style once processing starts)

Is this assessment accurate ? If so, how could this be fixed ?

**Comment by ggrossetie** [comment]
Hey @Ayowel 
You are correct, though it should still be possible to perform synchronous modular loading. This is a known limitation since the code is transpiled from Ruby to JavaScript. We are using https://github.com/ggrossetie/unxhr to perform synchronous HTTP calls in Node.

Since this is an open-ended discussion, I don't want to expand on this topic here. For reference, the issue tracker is reserved for bug reports and feature requests. If you want to continue this discussion please join and ask your question(s) on https://asciidoctor.zulipchat.com/
