### ISSUE TITLE
Proposition: embed the asciidoctor styles: foundation, colony, ...

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor.js#213]
During the build process of the npm module of asciidoctor, the `asciidoctor.css` file is packaged under the css directory (https://github.com/asciidoctor/asciidoctor.js/blob/master/npm/builder.js#L356).

As the `asciidoctor-stylesheet-factory` [project](https://github.com/asciidoctor/asciidoctor-stylesheet-factory) also proposes additional styles like foundation, colony, github, iconic, golo, ... I suggest to embed them too.

Make sense ?

**Comment by mojavelinux** [comment]
If we publish additional stylesheets, it should be done through a separate npm package. The default stylesheet is a minimum requirement for Asciidoctor to function (since it adds the styles by default in a standalone document). Anything non-essential should be a separate package.

I'm hesitant about packaging the other stylesheets from the stylesheet factory as they aren't tested at the moment for completeness or quality assurance. If we did package/ship stylesheets, I'd be more inclined to support the newer effort by @darshandsoni at https://github.com/darshandsoni/asciidoctor-skins. (I owe a follow-up on that thread).

I support the the effort to give users the capability to select alternative skins / themes. I just think it needs to be done as an add-on, not bundled into the core package in an effort to keep the core package streamlined.

**Comment by cmoulliard** [comment]
See my comment here : https://github.com/darshandsoni/asciidoctor-skins/issues/13#issuecomment-243374844

**Comment by Mogztter** [comment]
I agree that additional stylesheets should be provided as a separate npm package.
See https://github.com/mogztter/asciidoctor-stylesheets
