### ISSUE TITLE
userguide_test.html & asciidoctor_example.html examples contain an empty body

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor.js#216]
The 2 examples `userguide_test.rb` and `asciidoctor_example.rb` generate  HTML with an empty body.

See code source after

```xml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Asciidoctor in JavaScript powered by Opal</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700">
    <link rel="stylesheet" href="../asciidoctor.css">
  </head>
  <body>
    <div id="content"></div>
    <script src="../../bower_components/opal/opal/current/opal.js"></script>
    <script src="../asciidoctor-core.js"></script>
    <script src="userguide_test.js"></script>
  </body>
</html>
````
This empty body could be related to different problems 

1) The opal js dependency  is not there and then opal hasn't been started to execute the js script

![screenshot 2016-09-01 17 54 29](https://cloud.githubusercontent.com/assets/463790/18174264/3776e006-706d-11e6-9f68-74569b8f2bc9.png)

RESOLUTION : Execute bower install ! 

2) The browser will report a Cross origin issue. 

RESOLUTION : This issue could be resolved if we start locally a http server using by example the node module http-server

$ http-server -a localhost

![screenshot 2016-09-01 18 00 23](https://cloud.githubusercontent.com/assets/463790/18174473/fd9c0428-706d-11e6-9ed6-0aface4209f8.png)

**Comment by Mogztter** [comment]
If you are viewing these files with Firefox, it should work.
Chrome doesn't allow to include/load "file:///" for security reason
(cross-orign)

Le 1 sept. 2016 6:14 PM, "Charles Moulliard" <notifications@github.com> a
écrit :

Closed #216 <https://github.com/asciidoctor/asciidoctor.js/issues/216>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/asciidoctor/asciidoctor.js/issues/216#event-775400081>,
or mute the thread
