### ISSUE TITLE
Make Asciidoctor module available through UMD

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#225]
The [UMD (Universal Module Definition)](https://github.com/umdjs/umd) pattern typically attempts to offer compatibility with the most popular script loaders of the day (e.g RequireJS amongst others).

`Opal` global object is progressively disappearing from the public API (see #180).

We want to create a consistent way of using Asciidoctor.js in the client (browser) and in the server (Node.js).
##### Browser

``` javascript
var html = Opal.Asciidoctor.convert(content);
console.log(html);
```
##### Server

``` javascript
var asciidoctor = require('asciidoctor.js')();

var processor = null;
var useExtensions = true;

if (useExtensions) {
  processor = asciidoctor.Asciidoctor(true);
}
else {
  processor = asciidoctor.Asciidoctor();
}

var html = processor.convert(content);
console.log(html); 
```
##### Browser

``` javascript
var html = Asciidoctor.convert(content);
console.log(html);
```
##### Server

``` javascript
var Asciidoctor = require('asciidoctor.js'); // with extensions by default
// var Opal = require('opal-runtime'); // (optional if needed)

var html = Asciidoctor.convert(content);
console.log(html); 
```

**Comment by mojavelinux** [comment]
I support this proposal. The API still feels a bit too lab-oriented at the moment. We need to present a more consumable interface.

Since extensions have proved useful in JavaScript, I support including them to the asciidoctor.js module.

I'll also point to https://github.com/asciidoctor/asciidoctor.js/blob/master/benchmark/run.js, which reveals the complex situation with server-side JavaScript (Node, Phantom, Nashorn, Rhino) we're trying to normalize.

**Comment by cmoulliard** [comment]
Excellent idea to use UMD. +1
