### ISSUE TITLE
Remove the extensions-lab submodule ?

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#311]
Now that we can write extensions in JavaScript, maybe we should remove the git submodule on the [asciidoctor-extensions-lab](https://github.com/asciidoctor/asciidoctor-extensions-lab) repository ?

Advantage
 * Simplify the build
 * Provide examples on how to write extensions in JavaScript

Drawback
 * We will need to rewrite the following extensions and maintain both the Ruby and JavaScript code base:
   * chrome-inline-macro
   * man-inline-macro
   * emoji-inline-macro
   * chart-block-macro

**Comment by mojavelinux** [comment]
I'm in 100% agreement. I was thinking the same.

Most of these modules are not very complicated, so I'm not worried about the maintenance. The chart macro clearly needs to become it's own project, and we can publish official versions from there.

I don't really think that Asciidoctor.js (core) should be providing extensions anyway. These really should be separate projects now that we have proper packaging. (I mean, if left-pad can be a module, then...)

I my mind, we had these as part of the project since there wasn't an easy way to compile before. But that's all changing with your Opal helper projects as well as a native extension API. So the project is growing out of its old shell.

**Comment by mojavelinux** [comment]
I'd like to get input from @hsablonniere as well.
