### ISSUE TITLE
Cannot install with npm from git

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#340]
I tried to install asciidoctor.js from master to benefit from the latest commits.
However, I ended up having only 3 files on my disk:

```
$ npm install https://github.com/asciidoctor/asciidoctor.js.git
$ ls node_modules/asciidoctor.js
LICENSE      README.adoc  package.json
```

I understood (and learned about) `package.json#files`:

```
  "files": [
    "dist/asciidoctor.js",
    "dist/extensions",
    "dist/css",
    "LICENSE",
    "README.adoc"
  ]
```

The problem being with git, the `dist` folder is not versioned.

Can I suggest `master` to be deployed on npm with a special tag?
Cf. https://docs.npmjs.com/cli/publish

```
$ npm publish --tag dev

# on a different machine

$ npm install asciidoctor.js@dev
```

I am happy to create a PR to automate the publishing on npm from TravisCI.

**Comment by Mogztter** [comment]
Yes it could be super nice ;)
This tag/version published on npm can be replaced/updated ?


Le 13 juin 2017 11:40 AM, "Thomas Parisot" <notifications@github.com> a
écrit :

I tried to install the asciidoctor.js from master to benefit from the
latest commits.

However, I ended up having only 3 files on my disk:

$ npm install https://github.com/asciidoctor/asciidoctor.js.git
$ ls node_modules/asciidoctor.js
LICENSE      README.adoc  package.json

I understood (and learned about) package.json#files:

  "files": [
    "dist/asciidoctor.js",
    "dist/extensions",
    "dist/css",
    "LICENSE",
    "README.adoc"
  ]

The problem being with git, the dist folder is not versioned.

Can I suggest master to be deployed on npm with a special tag?
Cf. https://docs.npmjs.com/cli/publish

$ npm publish --tag dev

# on a different machine

$ npm install asciidoctor.js@dev

I am happy to create a PR to automate the publishing on npm from TravisCI.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/asciidoctor/asciidoctor.js/issues/340>, or mute the
thread

**Comment by oncletom** [comment]
> This tag/version published on npm can be replaced/updated ?

Ah, this is a good one! I think it is impossible to publish the same version without unpublishing it first. Maybe we can use a combination of both `package.json#version` + git tag to compose the npm published version (eg: `1.5.6-preview.1-master-at-abcedf0123`) — the alias `dev` can be pointed to any published version at anytime.

**Comment by mojavelinux** [comment]
> I am happy to create a PR to automate the publishing on npm from TravisCI.

However happy you are, I'll be 100x as happy.

I really want to move towards automating all the releases in Asciidoctor. And I hope that each time we do it, the other projects can learn and evolve so that we have to think as little as possible to make releases.

**Comment by mojavelinux** [comment]
cc: @ldez in case you'd like to share some advice to help this along. You are the master of releases in my mind.

**Comment by ldez** [comment]
For me publish all commit on master as a version in NPM is a bad idea:
- when we add a dependency, we use `npm -i lib` without version. This takes the last version on NPM.
- it's not a common way to publish on NPM.

I will doing a review of the PR.

**Comment by ldez** [comment]
If you really want do that, you must create a exit mode manageable by the Travis UI.

**Comment by ldez** [comment]
I want to precise: when I speak od "each commit on master" I want say "experimental version".
If we speak about only real release on tag, I'm totally agree.

**Comment by oncletom** [comment]
@ldez proposed publishing model is the following:

* `vX.Y.Z` -> `asciidoctor.js@latest` -> `npm i asciidoctor.js`
* `master` -> `asciidoctor.js@dev` -> `npm i asciidoctor.js@dev`

I admit it is a bit overkill to publish master on npm — installing asciidoctor.js as an npm dependency from git master is not trivial. Can you think of another way of proceeding?

**Comment by Mogztter** [comment]
Since the `dist` folder is not available on `master`, publishing `asciidoctor.js@dev` allow devs to use the latest changes (whitout building asciidoctor.js locally).

But arguably we could also publish preview versions more frequently.

Otherwise I agree with Dan, we should let Travis do the release (I will be way more confident to make a new release).
