### ISSUE TITLE
Include paths resolved differently between v1.5.5-4 and v1.5.6-preview.3

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#379]
Hello,

I have tried to upgrade from `asciidoctor.js@1.5.5-4` to `asciidoctor.js@v1.5.6-preview.3` but I stumbled on a problem related to include path resolution. I have not made any change to my build, I simply bumped asciidoctor dependency.

I includes files as following:

```adoc
include::../resources/tip-versions.adoc[]
include::../resources/tip-examples.adoc[]
```

On the generated HTML, I then see:

```
Unresolved directive in index.adoc - include::../resources/tip-versions.adoc[] Unresolved directive in index.adoc - include::../resources/tip-examples.adoc[]
```

And in my terminal shell, I see these warnings:

```
asciidoctor: WARNING: index.adoc: line 31: include file not found: /Users/oncletom/workspace/nodebook/chapter-06/resources/tip-versions.adoc
asciidoctor: WARNING: index.adoc: line 32: include file not found: /Users/oncletom/workspace/nodebook/chapter-06/resources/tip-examples.adoc
```

If I revert back to `asciidoctor.js@1.5.5-4` or `asciidoctor.js@1.5.5-5`, it is okay again.

Is it an expected change to do? I seem not to have seen anything in the releases changelog referring to this.

Thanks a lot for your help :-)

**Comment by Mogztter** [comment]
Strange... Can I reproduce this issue if I checkout [oncletom/nodebook](https://github.com/oncletom/nodebook) `master` branch and upgrade Asciidoctor.js to `1.5.6-preview.3` ?

**Comment by oncletom** [comment]
@Mogztter yes exactly 😸  I have tried with `1.5.6-preview.2` and had the same issue.

**Comment by Mogztter** [comment]
Good catch :fish: 
I think I found the root cause. We are now using the "default" method to read file as per: https://github.com/asciidoctor/asciidoctor/commit/ed67065104be760ff66cab8b83a60b8a02742e66#diff-9f52e64185d6eaeea012017fc43a9fa0

Basically it means that we are no longer using a special case for Node (since Opal Node implementation has all the necessary I/O methods).

Unfortunately the `File.expand_path` does not behave exactly the same in MRI and Node:

```ruby
::File.expand_path 'chapter-01/index.adoc'
# "/home/guillaume/workspace/opensource/nodebook/chapter-01/index.adoc"
```


```js
Opal.const_get_qualified('::', 'File').$expand_path('chapter-01/index.adoc');
// "chapter-01/index.adoc"
```

I think there's a missing case in here:
https://github.com/opal/opal/blob/7d75e7f2c1b1b4d2ea6117c0e63b13ad7e14023b/opal/corelib/file.rb#L9-L24

As a workaround you add a leading '.' before your path:

```js
// HACK: prefix the source file with "./" to make relative include work
processor.convertFile('./' + SOURCE_FILE, {
  'to_file': `${BUILD_DIR}/${destinationFile}`,
  'mkdirs': true,
  'safe': 'unsafe',
  'backend': 'html5',
  'doctype': 'book',
  'attributes': DEFAULT_ATTRIBUTES
});

**Comment by oncletom** [comment]
Lovely thinking! Did not even think of prefixing nor providing absolute paths…

Thanks for the detailed and prompt response, it totally works :-)
