### ISSUE TITLE
Don't include opal-runtime in npm package

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#396]
I'd really prefer if opal-runtime wasn't bundled inside the npm package. This is counter to how npm works and it adds unnecessary bloat to the package. Since the package is already including a generated file, I think we can configure the build to exclude opal-runtime for the file that gets included in the npm package.

I can understand bundling opal-runtime inside the distribution file hosted on CDNs, since they don't benefit from the dependency system that node / npm offers.

**Comment by Mogztter** [comment]
> I'd really prefer if opal-runtime wasn't bundled inside the npm package. This is counter to how npm works and it adds unnecessary bloat to the package. Since the package is already including a generated file, I think we can configure the build to exclude opal-runtime for the file that gets included in the npm package.

While I agree, the only alternative I can think of, is to publish two files:

* `asciidoctor.js`: uses `require` to resolve dependencies
* `asciidoctor-standalone.js`: bundles every dependencies in a single file

If we don't want to introduce a breaking change, `asciidoctor.js` should not be renamed but I can't think of another name.

> I can understand bundling opal-runtime inside the distribution file hosted on CDNs, since they don't benefit from the dependency system that node / npm offers.

It's a little more subtle than that since JavaScript "bundler" (like Webpack or Parcel) can be used to resolve `import`/`require` directives.

I think we will also need to update the README because front-end vs back-end development does not make much sense (ie. if your environment can resolve `require` then use `asciidoctor.js` otherwise use `asciidoctor-standalone.js`).

**Comment by Mogztter** [comment]
We could also provide a dedicated version per JavaScript environments like https://moment.github.io/luxon/docs/manual/install.html

* `build/node/asciidoctor.js`
* `build/amd/asciidoctor.js`
* `build/global/asciidoctor.js` (browser)
* `build/nashorn/asciidoctor.js`
* `build/es6/asciidoctor.js` (soon 😉)

**Comment by Mogztter** [comment]
I'm thinking about keeping the `dist/asciidoctor.js` as an UMD.
In addition we will also provide a dedicated version of Asciidoctor.js for each targeted environment/platform.

What do you think ?

**Comment by Mogztter** [comment]
For web bundler (Webpack...) I think we can use the `browser` hint in the `package.json`: https://github.com/defunctzombie/package-browser-field-spec

Currently Webpack wants to resolve the `fs` module because the code is common between all the targeted environment. So even if at runtime we will not used the `fs` module in a browser environment, Webpack throws an error.

**Comment by mojavelinux** [comment]
I'll look over the options you've presented this weekend. I've been really busy with Antora, but I'm due for a break.

**Comment by mojavelinux** [comment]
> We could also provide a dedicated version per JavaScript environments like moment.github.io/luxon/docs/manual/install.html

I like this proposal.



> I'm thinking about keeping the dist/asciidoctor.js as an UMD.

I'm fine with that. I'm not so concerned about which file gets loaded, just that node loads only what's needed.

> For web bundler (Webpack...) I think we can use the browser hint in the package.json: 

:+1: 

So we'd end up with:

So package.json would read:

```
"main": "dist/node/asciidoctor.js",
"browser": "dist/asciidoctor.js"
```

right?

**Comment by Mogztter** [comment]
> So package.json would read:
```
"main": "dist/node/asciidoctor.js",
"browser": "dist/asciidoctor.js"
```

Almost, I will use a dedicated version for the browser environment because the UMD version has references on Node modules. And when Webpack is processing `dist/asciidoctor.js`, it will try to resolve the Node modules (even though these modules won't be used at runtime in a browser environment).

So we'd end up with:

```
"main": "dist/node/asciidoctor.js",
"browser": "dist/browser/asciidoctor.js"
```

**Comment by mojavelinux** [comment]
Now I've got it. Thanks for clarifying!
