### ISSUE TITLE
Figure out how to speed up Asciidoctor.js

### ISSUE THREAD

**Issue by anthonny** [asciidoctor/asciidoctor.js#51]
Some tools : 
https://developer.chrome.com/devtools/docs/cpu-profiling

http://octane-benchmark.googlecode.com/svn/latest/index.html

**Comment by mojavelinux** [comment]
I noticed that the last version of v8 is getting faster and faster. Here's the timing loop for rendering the AsciiDoc Python user guide (which has been a benchmark for Asciidoctor since the beginning) using node.

node 0.12

```
Load scripts: 0.261s
Run #1: 1.217s
Run #2: 0.897s
Run #3: 0.766s
Run #4: 0.742s
```

node 5.3.0
```
Load scripts: 0.253s
Run #1: 1.08s
Run #2: 0.857s
Run #3: 0.673s
Run #4: 0.691s
```

(Good to know that Asciidoctor.js works with node v5.3.0).

In comparison, Asciidoctor running on Ruby 2.3.0 converts it in 0.18s.

We should probably create a benchmark folder in Asciidoctor.js so that we can easily get results to compare between versions. I have a script that I could commit. I'll propose it in a PR.

**Comment by mojavelinux** [comment]
Is it possible to profile using node? It seems like it would be a lot easier to automate.

**Comment by mojavelinux** [comment]
Here are the timings using jjs / nashorn 1.8.0_51.

```
Load scripts: 5.265s
Run #1: 30.995s
Run #2: 18.884s
Run #3: 13.255s
Run #4: 10.513s
```

**Comment by mojavelinux** [comment]
As promised, #161.

For some reason, phantomjs can't resolve the include directive, so I can't get results for phantom. I haven't been able to figure out why yet.

**Comment by mojavelinux** [comment]
Got it working with PhantomJS 1.9.8:

```
Load scripts: 0.085s
Run #1: 1.169s
Run #2: 1.146s
Run #3: 1.152s
Run #4: 1.169s
```

**Comment by Mogztter** [comment]
Thanks to Dan we have a benchmark script (and on recent version of Node.js it's pretty to use the built-in profiler).
