### ISSUE TITLE
How do I include the default theme?

### ISSUE THREAD

**Issue by stijnherreman** [asciidoctor/asciidoctor.js#512]
I've tried various methods of including the default theme by trying things mentioned in issues here, but whatever I try, there is no trace of any CSS. No inline stylesheet, no link to a CSS file.

What exactly do I need to do, for the default stylesheet to be used?

This is my build script:

```js
const asciidoctor = require("asciidoctor.js")();
const fs = require("fs-extra");
const glob = require("glob");

glob("src/**/*.adoc", (err, matches) => {
  if (err) throw err;

  for (let sourceFilePath of matches) {
    const fileContent = fs.readFileSync(sourceFilePath);

    const html = asciidoctor.convert(fileContent, {
      attributes: {
        safe: "unsafe",
        doctype: "article",
        header_footer: true,
        showtitle: true,
        attributes: ["copycss"]
      }
    });

    const targetFilePath = sourceFilePath
      .replace(new RegExp("^src/"), "dist/")
      .replace(new RegExp(".adoc$"), ".html");

    fs.outputFileSync(targetFilePath, html);

    console.log(`${sourceFilePath} => ${targetFilePath}`);
  }
});
```

I previously used AsciidocFX and theming worked out of the box there.

**Comment by stijnherreman** [comment]
Well, this is embarrassing. After spending over an hour on it and finally posting here, I spotted the error. This works better :smile:

```js
    const html = asciidoctor.convert(fileContent, {
      safe: "unsafe",
      doctype: "article",
      header_footer: true,
      showtitle: true,
      attributes: ["copycss"]
    });
```

**Comment by Mogztter** [comment]
Hello @stijnherreman and thanks for the follow-up.
I think we need to add an entry in the user manual. I'm curious, how did you spot your error and why did you encapsulate the options in an `attributes` object ? I just want to know to improve the documentation 😉 

Thanks

**Comment by stijnherreman** [comment]
I might have picked it up from the example code at https://github.com/asciidoctor/asciidoctor.js/issues/100 and https://github.com/asciidoctor/asciidoctor.js/issues/220, plus some copy pasting from another issue I can't find anymore.

Basically I was throwing things against the wall and seeing what sticks, on a hot Friday afternoon 😄 

It would be great if you could expand the example code in README.adoc to demonstrate some common options.

**Comment by Mogztter** [comment]
> I might have picked it up from the example code at #100 and #220, plus some copy pasting from another issue I can't find anymore.
Basically I was throwing things against the wall and seeing what sticks, on a hot Friday afternoon smile


Thanks for your feedback! :wink: 

Actually I think you can simplify your options. The following should be enough:

```js
const html = asciidoctor.convert(fileContent, {
  safe: 'safe',
  header_footer: true
});
```

When you generate a document the default stylesheet will be embedded into the HTML output by default (when the safe mode is less than `secure`).

And since you are converting an AsciiDoc-formatted string (and not a File) you need to explicitly define `header_footer: true` because, by default, the header and footer are excluded when converting an AsciiDoc-formatted string. This decision was made in order to make Asciidoctor consistent with other lightweight markup engines like Markdown.

You could also do the following:

```js
const html = asciidoctor.convertFile(sourceFilePath, {
  safe: 'safe',
  to_file: false
});
```

Here I'm using the `convertFile` function instead of the `convert` function. By default this function will write a file in the same directory as `sourceFilePath` (using the file name + the `html` extension).
But you can capture the HTML 5 output in a variable instead of writing it to a file by using the `to_file: false` option.

In this case I don't need `header_footer: true` because I'm using a File and by default the header and footer are included.

> It would be great if you could expand the example code in README.adoc to demonstrate some common options.

I've opened a pull request to improve the user manual (Getting started section): https://github.com/asciidoctor/asciidoctor.js/pull/513/files

The documentation will be available here: https://asciidoctor-docs.netlify.com

I don't know if it's a good idea but I want to keep the README as simple possible. As you can see it takes a few paragraphs to explain how include the default stylesheet :smile:

**Comment by stijnherreman** [comment]
The simplified options work, thank you. And the PR is looking good :smile:
