### ISSUE TITLE
Option to run as a single file (without dependencies) on Node

### ISSUE THREAD

**Issue by bimlas** [asciidoctor/asciidoctor.js#539]
I try to make an [Asciidoctor plugin for TiddlyWiki](https://bimlas.gitlab.io/tw5-asciidoctor/) ([source code](https://gitlab.com/bimlas/tw5-asciidoctor)).

TiddlyWiki is a wiki application which can be run (at least) in two ways:
- As a [standalon, single HTML file](https://tiddlywiki.com/#Empty%20Edition) (contains the Javascript, HTML and CSS code)
- [Running on Node](https://github.com/Jermolene/TiddlyWiki5#installing-tiddlywiki-on-nodejs)

My plugin works when the single HTML is used, but does not work on Node. As I figured out, the root of the problem is that I'm using `browser/asciidoctor.js` as is, Opal and other dependencies are not installed. This causing an error on Node because of these lines:

browser/asciidoctor.js
```javascript
if (typeof Opal === 'undefined' && typeof module === 'object' && module.exports) {
Opal = require('opal-runtime').Opal;
}
```

`module` is object, because I'm running on Node, but Opal module is not installed because I like to run use this single file like I do in browser.

Is it possible to discard the 'require' mechanism and use asciidoctor.js without dependencies on Node?

**Comment by Mogztter** [comment]
Hello @bimlas 

Just to clarify, you are using Node.js but you don't want to use `npm` (or `Yarn`) to install dependencies ?
I think you need to use a web bundler (webpack, parcel...) to create a single file that contains all the dependencies.

Please note that `browser/asciidoctor.js` is designed specifically for web browsers and contains specific code that relies on browser features (like `XMLHttpRequest`).
If you are running in a Node environment, you should use `node/asciidoctor.js`. Among other things, this file will read files using the Node.js `fs` module instead of `XMLHttpRequest` object.

You could also replace the line `require('opal-runtime')` with the actual code but it will be  a bit tedious to do that by hand.

**Comment by bimlas** [comment]
Hi @Mogztter 

Thanks for the fast reply.

TiddlyWiki can be run as a single HTML (in this case Node is not used) or as a Node script, but the plugin has to work in both cases - this is why I like to use it on Node as I do in the browser.

I don't know the details (and I'm a beginner in Javascript) but as I know, the difference between Node/HTML version is that Tiddly handles the "file saving" differently, but the main code is the same.

If I doing a webpack, will it work in the browser without Node?

**Comment by bimlas** [comment]
Commenting out the `require` lines and using `XMLHttpRequest` directly solved the problem.

```javascript
var asciidoctor_parser = require("$:/plugins/bimlas/asciidoctor/asciidoctor")({
  runtime: {
    ioModule: 'xmlhttprequest'
  }
});
```

Thanks!

**Comment by Mogztter** [comment]
No worries, I'm glad you've found a solution :muscle: 

Have fun with Asciidoctor.js :wink:
