### ISSUE TITLE
Write the version and lifecycle policies

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#597]
### Versioning 

* Before 2.x, Asciidoctor.js versions are aligned with Asciidoctor core Ruby
* After 2.x, Asciidoctor.js will use semantic versioning

The general rule is to provide bug fixes on the most recent version.

### Node.js support

* Use the latest active LTS:
When an active LTS goes into maintenance, Asciidoctor.js will switch to the next active LTS. For instance Node.js 8 LTS will enter maintenance in April 2019. Before this date, Asciidoctor.js will require Node.js 8 LTS. After this date Asciidoctor.js will require Node.js 10 LTS

### Browsers support

* last 1 version
* usage > 1% 

https://caniuse.com/usage-table
https://github.com/browserslist/browserslist

Asciidoctor.js may work on older version using Polyfill but it's not guaranteed.

### Nashorn support

Not actively maintained, efforts should be put on GraalVM.

### GraalVM support

Latest stable version.

//cc @mojavelinux

**Comment by mojavelinux** [comment]
Defining the version and lifecycle policy is a great idea.

> Asciidoctor.js will use semantic versioning

Since there's some confusion about how semantic versioning is interpreted in practice, I think the policy should state the rules as we define them. Specifically, what's the scope of a major, minor, and patch release (what's in, what's out, what criteria triggers a version number change). It doesn't have to be elaborate. The simpler the better.

The policy should also be very clear about where changes go. Changes are not backported to older versions (major and minor) unless there's a good reason (blocker or security). Generally, bug fixes go into the current minor version (which can spawn patch releases). Enhancements go into the next minor version (and bring with it bug fixes if the release is near). Breaking changes / major shifts go in the next major version, which pulls everything else with it when it's about to happen. I kind of think of the version numbers as having relative gravity. They pull the smaller changes with them when the release is near. Let's work on that statement to make it clear.
