### ISSUE TITLE
Issue a warning if a syntax highlighter is not found ?

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#661]
Asciidoctor core now provides a pluggable system for syntax highlighters. Basically you can now register syntax highlighters or even provide a factory to resolve syntax highlighters.

Out of the box Asciidoctor.js provides 2 syntax highlighters:

* `highlight.js` (also known as `highlightjs`, though this name will probably be deprecated in the future)
* `html-pipeline`

Previously, if `coderay` or `pygment` were used the following warning message was issued:

```rb
optional gem '#{gem_name}' is not installed. Functionality disabled.
```

But with the new pluggable system `coderay` and `pygment` are no longer hard-wired into core so the warning message is gone.

So now If I'm using the following AsciiDoc document:

```
:syntax-highlighter: coderay

[source,js]
----
console.log('hello');
----
```

Asciidoctor.js will silently ignore the syntax highlighter and produce the following output:

```html
<div id="content">
  <div class="listingblock">
    <div class="content">
      <pre class="highlight"><code class="language-js" data-lang="js">console.log('hello');</code></pre>
    </div>
  </div>
</div>
```

Should we add a warning message if the requested syntax highlighter is not available ?

**Comment by mojavelinux** [comment]
> html-pipeline

I'm going to disable this by default for Asciidoctor.js since it's really only intended for the GitHub integration.

**Comment by mojavelinux** [comment]
> Should we add a warning message if the requested syntax highlighter is not available?

I don't think an Asciidoctor core provider (Asciidoctor, Asciidoctor.js, AsciidoctorJ) should issue a warning. The source-highlighter is just a suggestion. However, the extension API is there for a developer to add this behavior when integrating Asciidoctor into an application. To do so, the developer can pass a custom syntax highlighter factory to the API.

If you want to preserve the existing behavior for coderay and pygments, since those are a) not available in Asciidoctor.js and b) previously issued a warning, then I'd support adding a custom adapter in Asciidoctor.js for those names that simply outputs a warning to the log.

We shouldn't be adding a blanket warning for all unknown source highlighters as that has the likelihood of causing a lot of unnecessary warnings.

**Comment by Mogztter** [comment]
> If you want to preserve the existing behavior for coderay and pygments, since those are a) not available in Asciidoctor.js and b) previously issued a warning, then I'd support adding a custom adapter in Asciidoctor.js for those names that simply outputs a warning to the log.
We shouldn't be adding a blanket warning for all unknown source highlighters as that has the likelihood of causing a lot of unnecessary warnings.

What about a debug message ?

**Comment by mojavelinux** [comment]
I think this is an appropriate use of a debug message.
