### ISSUE TITLE
How to build asciidoctor.js - after 2.0?

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#704]
Hello,

I'm not able to build Asciidoctor.js after version 2.0 changes. I see no build script in https://github.com/asciidoctor/asciidoctor.js/blob/master/package.json . Has building process been changed?

Additionally, can I build Asciidoctor.js against a specific Asciidoctor version in my filesystem?

**Comment by mojavelinux** [comment]
I think this section is what you are looking for:

https://github.com/asciidoctor/asciidoctor.js/blob/master/CONTRIBUTING-CODE.adoc#building

However, now that Asciidoctor.js has largely stabilized, and will be switching to semantic versioning, I strongly recommend using the packaged version instead of building it.

**Comment by Mogztter** [comment]
Arguably this is unclear because I state "Next, switch to the asciidoctor.js/packages/core directory..." in the Setup section and then I assume that all the commands in the Building section will also be ran from the asciidoctor.js/packages/core directory.
I also forgot to remove this sentence "To build Asciidoctor.js, simply run the npm build script from the root of the project:". 

Please note that it's possible to build Asciidoctor.js from the root of the project but the command should be:

```
npm run build --prefix packages/core
```

> I see no build script in https://github.com/asciidoctor/asciidoctor.js/blob/master/package.json . Has building process been changed?

Asciidoctor.js is now a modular package. The `package.json` at the root of the project is only there to release the project. Though we might add some features to build/test all the modules/packages at once.
Most of the code is now in `packages/core`.

I will mark this issue as "Documentation" as we need to improve the documentation before the 2.0.0 release.

**Comment by rahmanusta** [comment]
Thanks @mojavelinux @Mogztter ,

I need a little modified form of Asciidoctor to make it work with AsciidocFX, that's why I need it configurable to be able to get Asciidoctor core from file system.

Btw, `npm run build --prefix packages/core` command works from the root directory. Thanks for this hint. For sure, `npm install` should be run in root, packages/core, and packages/asciidoctor directories.

**Comment by mojavelinux** [comment]
> I need a little modified form of Asciidoctor to make it work with AsciidocFX, that's why I need it configurable to be able to get Asciidoctor core from file system.

I think we should really be incorporating that in so that you don't have to make a custom build, but rather just add additional configuration to the existing one.

**Comment by rahmanusta** [comment]
That's great. Good idea.

Basically, I need to things.

1. in file.rb#read method, it makes a get request directly to the path, can we have a configurable root path for this? root can be an "" empty string by default, and it can be updated by API user if needed.

For example if I set rootPath="/asciidocfx", the request can be made to rootPath + path

2. It looks :data-uri: doesn't work in Asciidoctor.js. It gives the following error

> ERROR => {"name":"binread","message":"undefined method `binread' for File","args":["./formula.png"]}

How do I handle :data-uri: in AsciidocFX? I first remove data-uri part in image_uri method, and use a [tree processor](https://github.com/asciidocfx/AsciidocFX/blob/master/conf/public/js/asciidoctor-data-uri.js), it does a service call and the service returns the base64 image.

**Comment by mojavelinux** [comment]
> in file.rb#read method, it makes a get request directly to the path, can we have a configurable root path for this

I think this is too low level. We should think about where and how the path gets resolved up in the Asciidoctor realm so by the time it goes to read the file, it's using the correct path. We need to know more about the use case.

> It looks :data-uri: doesn't work in Asciidoctor.js. It gives the following error

I think we're still working out an API for reading and generating a data-uri from an asset that works cleanly across all environments. I'm not convinced we have the API right yet.

**Comment by Mogztter** [comment]
> It looks :data-uri: doesn't work in Asciidoctor.js. It gives the following error

With Asciidoctor.js 1.5.9 right ?
We do have tests to cover this feature so I think it should work in Asciidoctor.js 2.0.0:
https://github.com/asciidoctor/asciidoctor.js/blob/dee362e9dc15b823a45acb446b9c65e8375cd484/packages/core/spec/share/asciidoctor-spec.js#L886-L919

In Asciidoctor.js 2.0.0 `binread` should not be called because we provide our own `generate_data_uri` method (and as far as I know this is the only place where Asciidoctor Ruby is calling `binread`):

https://github.com/asciidoctor/asciidoctor.js/blob/dee362e9dc15b823a45acb446b9c65e8375cd484/packages/core/lib/asciidoctor/js/asciidoctor_ext/browser/abstract_node.rb#L27

https://github.com/asciidoctor/asciidoctor.js/blob/dee362e9dc15b823a45acb446b9c65e8375cd484/packages/core/lib/asciidoctor/js/asciidoctor_ext/node/abstract_node.rb#L6

So you should be able to remove the TreeProcessor.

**Comment by mojavelinux** [comment]
My mistake, I assumed @rahmanusta was testing against 2.0.0 and was saying something still wasn't working. Let's wait to hear if the fix for data-uri works in AsciidocFx.

(But I still think we can do better with the API...though that shouldn't stop using the current solution).

**Comment by rahmanusta** [comment]
No, it is 2.0.0. 

`var ASCIIDOCTOR_JS_VERSION = '2.0.0-rc.1';`

> I think this is too low level. We should think about where and how the path gets resolved up in the Asciidoctor realm so by the time it goes to read the file, it's using the correct path. We need to know more about the use case.

In current implementation, resource root/root_url cannot be set. How can configure to load resources from a specific url ? For example I want resources to be resolved from the http://localhost:8080/resource.afx/{path} url. By default, it will request resources from domain of the webpage like http://localhost:8080/{path}, and no way to configure.

**Comment by Mogztter** [comment]
AsciidocFX is running Asciidoctor.js in Nashorn right ? I think that's why the implementation is not found. 
We've decided to drop support for Nashorn but you could provide your own implementation of `generate_data_uri_from_uri`.

**Comment by rahmanusta** [comment]
It's running on a browser's webworker, I set platform as browser.

I noticed that `generate_data_uri` is called with current AsciidocFX settings, I should align attributes to target only `generate_data_uri_from_uri` function, or implement own implementation as you suggest.

```
if ($truthy(($truthy($a = ($truthy($b = $$($nesting, 'Helpers')['$uriish?'](target_image)) ? (target_image = $$($nesting, 'Helpers').$encode_uri(target_image)) : $b)) ? $a : ($truthy($b = ($truthy($c = ($truthy($d = asset_dir_key) ? (images_base = doc.$attr(asset_dir_key)) : $d)) ? $$($nesting, 'Helpers')['$uriish?'](images_base) : $c)) ? (target_image = self.$normalize_web_path(target_image, images_base, false)) : $b)))) {
            if ($truthy(doc['$attr?']("allow-uri-read"))) {
              return self.$generate_data_uri_from_uri(target_image, doc['$attr?']("cache-uri"))
            } else {
              return target_image
            }
          } else {
            // here binread is called, it may give a warning to user if env is browser
            return self.$generate_data_uri(target_image, asset_dir_key)
          }
```

**Comment by mojavelinux** [comment]
> In current implementation, resource root/root_url cannot be set. How can configure to load resources from a specific url ?

When you say resolve resources, do you mean read the contents of a resource for the purpose of embedding it as a data-uri into the document? Or are you talking about the path used in an href/src in the HTML?

**Comment by rahmanusta** [comment]
I mean resources for example images inside document. All resources accessed by file.rb.

**Comment by mojavelinux** [comment]
But if it's accessed by file.rb, then you're imply that your using the data-uri feature. Otherwise, it would just be a link.

...and that is then covered by overriding the AbstractNode#normalize_system_path method. You should not be patching core Ruby methods.

Though even before you do that, this is the purpose of the base_dir option.

**Comment by rahmanusta** [comment]
Yes, this was the second question in addition to data-uri. I think base_dir option looks ideal for me.
