### ISSUE TITLE
The 2.x.x minified version of AsciiDoctor JS not working

### ISSUE THREAD

**Issue by ainslec** [asciidoctor/asciidoctor.js#717]
The minified version of Asciidoctor.js does not expose the Asciidoctor object. This problem does not exist in the non minified version.

![image](https://user-images.githubusercontent.com/201870/56040537-81425e80-5d2e-11e9-9670-c2b9a02c929e.png)

Location of release zip used : https://github.com/asciidoctor/asciidoctor.js/releases/download/v2.0.0/asciidoctor.js.dist.zip

If we create a test html file called test.html in the "browser" folder of the unzipped distribution, this issue can be demonstrated with the following code.

**NOT WORKING (minified does not have the Asciidoctor object exposed)**

```
<html>
<head>
<script src="asciidoctor.min.js"></script>
<script>
function test() {
var asciidoctor = Asciidoctor();
var html        = asciidoctor.convert('Hello, _Asciidoctor_');
var body        = document.body;
body.innerHTML = html;
}
</script>
</head>
<body onload="test()">
</body>
</html>
```

**WORKING (unminified working fine)**

```
<html>
<head>
<script src="asciidoctor.js"></script>
<script>
function test() {
var asciidoctor = Asciidoctor();
var html        = asciidoctor.convert('Hello, _Asciidoctor_');
var body        = document.body;
body.innerHTML = html;
}
</script>
</head>
<body onload="test()">
</body>
</html>
```

**Comment by Mogztter** [comment]
Thanks for your report @ainslec 
I can reproduce this issue. I think the root cause is:

```
asciidoctor.min.js:10 Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at p (asciidoctor.min.js:10)
    at Object.l.cd (asciidoctor.min.js:18)
    at asciidoctor.min.js:43
    at asciidoctor.min.js:45
```

**Comment by Mogztter** [comment]
We do not run the tests suite on the minifed file that's why we didn't catch this error.

I can confirm that the code produces by Clojure Compiler using the advanced compilation level is invalid. The root cause is that Opal uses `Object.defineProperty` to define properties on object.
Here's a simplified example:

```js
var obj = {}

function defineProperty (object, name, value) {
  Object.defineProperty(object, name, {
    value: value,
    enumerable: false,
    configurable: true,
    writable: true
  })
}

defineProperty(obj, 'foo', { value: 'foo' })
defineProperty(obj.foo, 'bar', { value: 'bar' })
```

So we define a property `foo` on the object `obj` and then we define a property `bar` on the `obj.foo` object. The problem is that Clojure Compiler doesn't understand that we have define a property named `foo`. So during the optimization the attribute foo will be renamed. Here's the minified code:

```js
var a = {}

function b (c, d, e) {Object.defineProperty(c, d, { value: e, enumerable: !1, configurable: !0, writable: !0 })}

b(a, 'foo', { value: 'foo' })
b(a.a, 'bar', { value: 'bar' }) // wrong it should be "a.foo"
```

So now we still define an attribute named `foo` but `obj.foo` was renamed to `a.a` :disappointed: 
To be fair, the compiler did issue a warning:

```
define.js:13: WARNING - Property foo never defined on obj
defineProperty(obj.foo, 'bar', { value: 'bar' })
                   ^^^

0 error(s), 1 warning(s), 83.3% typed
```

I don't think we should try to rewrite Opal code in order to make it compatible with Clojure Compiler (it will probably won't work).

So we should probably use the default compilation level:

```
612K  asciidoctor-browser-advanced.min.js
717K  asciidoctor-browser-default.min.js
```

@mojavelinux Thoughts ?

**Comment by mojavelinux** [comment]
We gotta do what we gotta do. I would just document this reasoning on the page about producing a minified version so that we remember (and others don't get tripped up).

I think long term, Opal should focus on producing code that can be maximally optimized. It's a core requirement for being able to run in the browser. (In contrast, it's not important at all for running it with Node).

**Comment by Mogztter** [comment]
We should maybe try other minify libraries:

- https://github.com/mishoo/UglifyJS2

Or at least add a mention in #655

**Comment by Mogztter** [comment]
UglifyJS produces a (slightly) bigger file:

```
725K asciidoctor-browser-uglifyjs.min.js
```

**Comment by ainslec** [comment]
I'd say a bigger minified file that works is a good trade-off.

**Comment by mojavelinux** [comment]
From my experience using clojure, it's not that it doesn't work. It's just has certain modes that don't work, or that require additional annotations to mark what should't be remove. Then again, without those optimizations, you get back to the UglifyJS size.
