### ISSUE TITLE
Docinfo support

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#733]
Hello,

Does Asciidoctor.js support docinfo feature ? If yes, do you have an example for it?

Thanks
Rahman

**Comment by Mogztter** [comment]
It should work on Node.js but I've never tried and I'm not sure about using this feature in a browser environment.

But since you're asking I guess that you tried and it didn't work ?

In theory it should work the same way as Asciidoctor Ruby since it's the same code.
So you will need to create a file name `<docname>-docinfo.html`, then use `convertFile('<docname>.adoc')`.

I will add a test to cover this feature.

**Comment by rahmanusta** [comment]
It didn't work in Asciidoctor.js at first try, but I'll retry it later. I'll let you know about outcome.

**Comment by Mogztter** [comment]
Ok, you can check the tests: https://github.com/asciidoctor/asciidoctor.js/pull/734/files#diff-de27ea12d3004af5cce3323c63323b7fR1648

**Comment by Mogztter** [comment]
@rahmanusta is it working ?

**Comment by Mogztter** [comment]
@rahmanusta Any news? 🏓
