### ISSUE TITLE
Add TypeScript definitions for extensions and converters

### ISSUE THREAD

**Issue by robaca** [asciidoctor/asciidoctor.js#764]
It would be great to also have TypeScript definitions for the Extension and Converter APIs. It would especially be helpful to have a schema for the different Node types a converter can handle. I just wrote my first modification to the Html5Converter and had to look into the `asciidoctor` ruby source code to get an understanding what properties and functions are available. Having the type info at hand would make this a lot easier.

**Comment by Mogztter** [comment]
Hello @robaca 
Yes that would be nice! I don't use TypeScript myself so if you want to give it a try please feel free to submit a pull request: https://github.com/asciidoctor/asciidoctor.js/tree/master/packages/core/types

I've found [this article](https://dev.to/open-wc/generating-typescript-definition-files-from-javascript-5bp2#generate-typescript-definition-files-for-jsdoc-annotated-javascript) that explain how to generate TypeScript Definition Files for JSDoc Annotated JavaScript. Since we are using JSDoc maybe we can do that?

**Comment by Mogztter** [comment]
@robaca Do you plan to work on it? I'm asking because I will probably release a new version soon and I want to include a TypeScript definition as complete as possible.

**Comment by sondr3** [comment]
I dropped a comment on the PR, I might be able to help but am on vacation until the weekend.
