### ISSUE TITLE
Leveloffset artifact appears in table when using includes for rows.

### ISSUE THREAD

**Issue by Nadreck** [asciidoctor/asciidoctor.js#997]
In cases where you are creating a table, it is possible to use `include::` as the content for that table. This largely works, but if you have `leveloffset` set for that include file, it is included as an artifact in the rendered table:

```
[cols="3*a", options="header"]
|===
| Software
| Version
| URL for More Information

include::row-sw-docker-desktop.adoc[leveloffset=+2]

include::row-sw-kubectl.adoc[leveloffset=+2]
```

Results in:
<img width="787" alt="Leveloffset artifact at end of header column" src="https://user-images.githubusercontent.com/318316/83804390-e8be1a80-a662-11ea-867c-ebb47bee16f4.png">

(This was discovered in 1.5.9, since we're building with Antora.)

**Comment by mojavelinux** [comment]
The leveloffset can only be used on an include inside a single AsciiDoc table cell. The leveloffset adds an attribute entry above the included content, so it will end up falling outside of a table cell in this scenario.

p.s. Generally, you should only apply the AsciiDoc style to cells that have block content (since it requires more processing).

**Comment by Mogztter** [comment]
So this behavior is intended? Does it answer your question? Can we close this issue?

**Comment by Nadreck** [comment]
The behavior was unexpected, but with the explanation of how leveloffset is actually being handled, seems like working as intended.

**Comment by Mogztter** [comment]
Thanks for the follow-up 👍
